
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_exercise_db?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: HelloWorld123
    driver-class-name: com.mysql.cj.jdbc.Driver

  codec:
    max-in-memory-size: 2MB

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update          # change to "update" --> if you want to keep database for every web application restart
    show-sql: false             #      "create-drop" --> for recreating & drop every time for every restart (Debugging)
    properties:
      hibernate:
        format_sql: true

  main:
    web-application-type: servlet

edamam:
  api:
    base-url: "https://api.edamam.com/api/recipes/v2"
    app-id: "f4c412e5"
    app-key: "9c7b4bc458dbd46fb4cf30d0155bac42"

logging:
  level:
    com.upm.momcarerecommendation: info