package rules;

import com.upm.momcarerecommendation.domain.model.MotherRequest
import com.upm.momcarerecommendation.domain.model.FoodRecommend
import com.upm.momcarerecommendation.domain.model.NutritionRecommend

rule "Basic Nutrition Recommendation for Mother"
    when
        $mother : MotherRequest()
    then
        insert(new NutritionRecommend("nutrients[NA]", "1", $mother));
        insert(new NutritionRecommend("nutrients[PROCNT]", "5", $mother));
        insert(new FoodRecommend("diet", "low-sodium", $mother));
        insert(new FoodRecommend("diet", "low-carb", $mother));
        insert(new FoodRecommend("health", "vegetarian", $mother));
        insert(new FoodRecommend("health", "low-potassium", $mother));
end
