package rules;

import com.upm.momcarerecommendation.domain.MotherRequest
import com.upm.momcarerecommendation.domain.DetectedDisease
import com.upm.momcarerecommendation.domain.ExerciseRecommend

// Exercise Recommendation based on Health Condition
rule "Severe Blood Pressure Exercise"
salience -1
    when
        $mother : MotherRequest()
        DetectedDisease( diseaseName == "Blood Pressure" , severity == "Severe", mother == $mother)
    then
        insert(new ExerciseRecommend("All Activity", "Avoid", $mother));
end

rule "High Blood Pressure Exercise"
    when
        $mother : MotherRequest()
        DetectedDisease( diseaseName == "Blood Pressure" , severity != "Severe", mother == $mother)
    then
        insert(new ExerciseRecommend("High Intensity Activity", "Avoid", $mother));
end

rule "Anaemia Exercise"
    when
        $mother : MotherRequest()
        DetectedDisease( diseaseName == "Anaemia", mother == $mother)
    then
        insert(new ExerciseRecommend("High Intensity Activity", "Avoid", $mother));
end

rule "Postpartum women having C-Section"
    when
        $mother : MotherRequest( !isPregnant(), deliveryMethod == "C-Section" )
    then
        insert(new ExerciseRecommend("All Activity", "Avoid", $mother));
end

rule "Pregnant Women Exercise"
    when
        $mother : MotherRequest( isPregnant() )
    then
        insert(new ExerciseRecommend("Riding Stationary Bike", "Should", $mother));
        insert(new ExerciseRecommend("Modified Yoga", "Should", $mother));
        insert(new ExerciseRecommend("Supine Position Activity", "Avoid", $mother));
        insert(new ExerciseRecommend("High Falling Risk Activity", "Avoid", $mother));
        insert(new ExerciseRecommend("Hiking", "Avoid", $mother));
        insert(new ExerciseRecommend("Scuba Diving", "Avoid", $mother));
end

rule "Postpartum Women Exercise"
    when
        $mother : MotherRequest( !isPregnant() )
    then
        insert(new ExerciseRecommend("Joging", "Should", $mother));
end

rule "For All Mother Exercise"
    when
        $mother : MotherRequest()
    then
        insert(new ExerciseRecommend("Muscle-strengthening activities", "Should", $mother));
        insert(new ExerciseRecommend("Stomach Strengthening Exercise", "Should", $mother));
        insert(new ExerciseRecommend("Pelvic Floor Exercise", "Should", $mother));
        insert(new ExerciseRecommend("Swimming", "Should", $mother));
        insert(new ExerciseRecommend("Brisk Walking", "Should", $mother));
end