package rules;

import com.upm.momcarerecommendation.domain.model.MotherRequest
import com.upm.momcarerecommendation.domain.model.ExerciseRecommend

rule "First Trimester Pregnant Exercise"
    when
        $mother : MotherRequest( isPregnant() && trimester == 1 )
    then
        insert(new ExerciseRecommend("impactLevel", "Low"));
        insert(new ExerciseRecommend("intensityLevel", "Moderate"));
        insert(new ExerciseRecommend("suitableForPregnancyTrimester", "All Trimester"));
end
rule "Second Trimester Pregnant Exercise"
    when
        $mother : MotherRequest( isPregnant() && trimester == 2 )
    then
        insert(new ExerciseRecommend("impactLevel", "Low"));
        insert(new ExerciseRecommend("intensityLevel", "Moderate"));
        insert(new ExerciseRecommend("suitableForPregnancyTrimester", "2 Trimester"));
end
rule "Third Trimester Pregnant Exercise"
    when
        $mother : MotherRequest( isPregnant() && trimester == 3 )
    then
        insert(new ExerciseRecommend("impactLevel", "Low"));
        insert(new ExerciseRecommend("intensityLevel", "Low"));
        insert(new ExerciseRecommend("suitableForPregnancyTrimester", "3 Trimester"));
end

rule "Postpartum Exercise without C-Section"
    when
        $mother : MotherRequest( !isPregnant() && deliveryMethod != "C-Section" )
    then
        insert(new ExerciseRecommend("impactLevel", "Low"));
        insert(new ExerciseRecommend("impactLevel", "Moderate"));
        insert(new ExerciseRecommend("intensityLevel", "Low"));
        insert(new ExerciseRecommend("intensityLevel", "Moderate"));
end
rule "Postpartum Exercise with C-Section"
    when
        $mother : MotherRequest( !isPregnant() && deliveryMethod == "C-Section" )
    then
        insert(new ExerciseRecommend("impactLevel", "Low"));
        insert(new ExerciseRecommend("intensityLevel", "Low"));
end